# Generated by Django 4.1.7 on 2023-03-05 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='file',
            fields=[
                ('FileId', models.AutoField(primary_key=True, serialize=False)),
                ('File', models.CharField(max_length=256)),
                ('Name', models.CharField(max_length=256)),
                ('UserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
