# Generated by Django 4.1.7 on 2023-03-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Networkmap',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='analysisFile',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
