# Generated by Django 4.1.7 on 2023-03-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_file_networkmap_file_analysisfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='File',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
