# Generated by Django 4.1.7 on 2023-03-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_alter_file_networkmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='analysisFile',
        ),
        migrations.AddField(
            model_name='file',
            name='Networkips',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='mostactiveadd',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='protocols',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='susips',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
