# Generated by Django 4.1.7 on 2023-03-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_remove_file_name_remove_file_analysisfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='DDos',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='portflooding',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
