# Generated by Django 4.1.7 on 2023-04-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_networknodes_rename_protocols_file_protocols1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='protocols1',
            new_name='protocals1',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='protocols2',
            new_name='protocals2',
        ),
    ]
