# Generated by Django 4.1.7 on 2023-04-01 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0010_delete_interfaceuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTable',
            fields=[
                ('FileId', models.AutoField(primary_key=True, serialize=False)),
                ('File', models.FileField(null=True, upload_to='')),
                ('Networkmap', models.ImageField(upload_to='images')),
                ('Networkips', models.CharField(max_length=256, null=True)),
                ('protocals1', models.CharField(max_length=256, null=True)),
                ('protocals2', models.CharField(max_length=256, null=True)),
                ('mostactiveadd', models.CharField(max_length=256, null=True)),
                ('susips', models.CharField(max_length=256, null=True)),
                ('portflooding', models.CharField(max_length=256, null=True)),
                ('DDos', models.CharField(max_length=256, null=True)),
                ('UserId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Networknodes',
        ),
    ]
