# Generated by Django 4.1.7 on 2023-04-01 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interface', '0011_filetable_delete_networknodes'),
    ]

    operations = [
        migrations.CreateModel(
            name='interfaceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logincont', models.CharField(blank=True, max_length=135)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='file',
            old_name='protocals1',
            new_name='protocols',
        ),
        migrations.RemoveField(
            model_name='file',
            name='protocals2',
        ),
        migrations.DeleteModel(
            name='FileTable',
        ),
    ]
