# Generated by Django 4.1.7 on 2023-04-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_interfaceuser_rename_protocals1_file_protocols_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='Networkips',
            new_name='SourceIP',
        ),
        migrations.AddField(
            model_name='file',
            name='destinationIP',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
