# Generated by Django 4.1.7 on 2023-04-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0013_rename_networkips_file_sourceip_file_destinationip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='Networkmap',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
