# Generated by Django 4.1.7 on 2023-04-07 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0014_alter_file_networkmap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='protocols',
            new_name='protocol1',
        ),
        migrations.AddField(
            model_name='file',
            name='protocol2',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
