# Generated by Django 4.1.7 on 2023-04-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0015_rename_protocols_file_protocol1_file_protocol2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='protocol1',
            new_name='arp',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='protocol2',
            new_name='icmp',
        ),
        migrations.AddField(
            model_name='file',
            name='ssl',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='tcp',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='udp',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
