# Generated by Django 4.1.7 on 2023-04-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0017_file_sourcemac_file_destinationmac_file_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='UserId',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
