# Generated by Django 4.1.7 on 2023-04-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0018_alter_file_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='index',
            new_name='SourceIParp',
        ),
        migrations.AddField(
            model_name='file',
            name='Sourcemacarp',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='destinationIParp',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='destinationmacarp',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
