# Generated by Django 4.1.7 on 2023-04-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0020_file_ddos2'),
    ]

    operations = [
        migrations.CreateModel(
            name='file2',
            fields=[
                ('FileId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=256, null=True)),
                ('File', models.FileField(null=True, upload_to='')),
                ('Networkmap', models.ImageField(upload_to='images/')),
                ('SourceIP', models.CharField(max_length=256, null=True)),
                ('destinationIP', models.CharField(max_length=256, null=True)),
                ('Sourcemac', models.CharField(max_length=256, null=True)),
                ('destinationmac', models.CharField(max_length=256, null=True)),
                ('SourceIParp', models.CharField(max_length=256, null=True)),
                ('destinationIParp', models.CharField(max_length=256, null=True)),
                ('Sourcemacarp', models.CharField(max_length=256, null=True)),
                ('destinationmacarp', models.CharField(max_length=256, null=True)),
                ('arp', models.CharField(max_length=256, null=True)),
                ('udp', models.CharField(max_length=256, null=True)),
                ('icmp', models.CharField(max_length=256, null=True)),
                ('ssl', models.CharField(max_length=256, null=True)),
                ('tcp', models.CharField(max_length=256, null=True)),
                ('mostactiveadd', models.CharField(max_length=256, null=True)),
                ('susips', models.CharField(max_length=256, null=True)),
                ('portflooding', models.CharField(max_length=256, null=True)),
                ('DDos', models.CharField(max_length=256, null=True)),
                ('DDos2', models.CharField(max_length=256, null=True)),
            ],
        ),
    ]
